"""init tables

Revision ID: ff8e94b2ffb8
Revises: 
Create Date: 2026-01-10 04:27:37.493759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff8e94b2ffb8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_allergen_code')
    )
    op.create_index(op.f('ix_allergens_code'), 'allergens', ['code'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('form', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_medication_code')
    )
    op.create_index(op.f('ix_medications_code'), 'medications', ['code'], unique=False)
    op.create_index(op.f('ix_medications_form'), 'medications', ['form'], unique=False)
    op.create_table('symptoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_symptom_code')
    )
    op.create_index(op.f('ix_symptoms_code'), 'symptoms', ['code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('asit_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('regimen', sa.String(length=32), nullable=False),
    sa.Column('target_allergen_id', sa.Integer(), nullable=True),
    sa.Column('medication_id', sa.Integer(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('dose_unit', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['target_allergen_id'], ['allergens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asit_plans_user_id'), 'asit_plans', ['user_id'], unique=False)
    op.create_table('doctor_patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_patient_doctor_id'), 'doctor_patient', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_patient_patient_id'), 'doctor_patient', ['patient_id'], unique=False)
    op.create_table('patient_allergen',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('allergen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'allergen_id')
    )
    op.create_table('patient_allergy',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symptoms_start_date', sa.Date(), nullable=True),
    sa.Column('active_months', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('frequency', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('patient_medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('dose_text', sa.String(length=64), nullable=True),
    sa.Column('times_per_day', sa.Integer(), nullable=True),
    sa.Column('interval_hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_medications_medication_id'), 'patient_medications', ['medication_id'], unique=False)
    op.create_index(op.f('ix_patient_medications_user_id'), 'patient_medications', ['user_id'], unique=False)
    op.create_table('patient_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('patient_symptom',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'symptom_id')
    )
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('active_months', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_scheduled_at'), 'reminders', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.create_table('asit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('dose_value', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['asit_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asit_events_plan_id'), 'asit_events', ['plan_id'], unique=False)
    op.create_index(op.f('ix_asit_events_planned_date'), 'asit_events', ['planned_date'], unique=False)
    op.create_table('medication_intake_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_medication_id', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('tablets_per_day', sa.Integer(), nullable=True),
    sa.Column('effect', sa.String(length=16), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['patient_medication_id'], ['patient_medications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_intake_logs_patient_medication_id'), 'medication_intake_logs', ['patient_medication_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medication_intake_logs_patient_medication_id'), table_name='medication_intake_logs')
    op.drop_table('medication_intake_logs')
    op.drop_index(op.f('ix_asit_events_planned_date'), table_name='asit_events')
    op.drop_index(op.f('ix_asit_events_plan_id'), table_name='asit_events')
    op.drop_table('asit_events')
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_scheduled_at'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_table('patient_symptom')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_patient_medications_user_id'), table_name='patient_medications')
    op.drop_index(op.f('ix_patient_medications_medication_id'), table_name='patient_medications')
    op.drop_table('patient_medications')
    op.drop_table('patient_allergy')
    op.drop_table('patient_allergen')
    op.drop_index(op.f('ix_doctor_patient_patient_id'), table_name='doctor_patient')
    op.drop_index(op.f('ix_doctor_patient_doctor_id'), table_name='doctor_patient')
    op.drop_table('doctor_patient')
    op.drop_index(op.f('ix_asit_plans_user_id'), table_name='asit_plans')
    op.drop_table('asit_plans')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_symptoms_code'), table_name='symptoms')
    op.drop_table('symptoms')
    op.drop_index(op.f('ix_medications_form'), table_name='medications')
    op.drop_index(op.f('ix_medications_code'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_allergens_code'), table_name='allergens')
    op.drop_table('allergens')
    # ### end Alembic commands ###
